export const darkTheme = {
  primary: '#1D3D47',
  primaryText: '#FFFFFF',
  bgBottomColor: '#000000',
  colorBottomActive: '#cb70ff',
  colorBottomInactive: '#837c87',
  headerBgColor: '#cb70ff',
  headerTextColor: '#FFFFFF',
  bgModalAddGoal: '#1c1421',
  textColorTitleModalAddGoal: '#FFFFFF',
  dstBgColorGoal: '#44364a',
  datBgColorGoal: '#44364a',
  smBgColorGoal: '#44364a',
  homeBgColor: '#131714',
  goalTitleTextColor: '#FFFFFF',
  calendarE: 'green',
  calendarB: 'yellow',
  calendarO: 'red',
};
  